package com.sap.aii.tpm.internal.api;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "KeystoreServiceApi", targetNamespace = "http://sap.com/aii/tpm/internal/api/")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.WRAPPED, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface KeystoreServiceApi {

  /**
   * Java representation of web method [GetKeystoreCertificates].
   */
  @javax.jws.WebMethod(operationName = "GetKeystoreCertificates", action = "getKeystoreCertificates")
  @javax.xml.ws.RequestWrapper(localName = "GetKeystoreCertificates", targetNamespace = "http://sap.com/aii/tpm/internal/api/", className = "com.sap.aii.tpm.internal.api.GetKeystoreCertificates")
  @javax.xml.ws.ResponseWrapper(localName = "GetKeystoreCertificatesResponse", targetNamespace = "http://sap.com/aii/tpm/internal/api/", className = "com.sap.aii.tpm.internal.api.GetKeystoreCertificatesResponse")
  @javax.jws.WebResult(name = "KeystoreCertsList", targetNamespace = "")
  public java.util.List<com.sap.aii.tpm.internal.api.Certificate> getKeystoreCertificates(@javax.jws.WebParam(name = "KeystoreName", targetNamespace = "") java.lang.String keystoreName, @javax.jws.WebParam(name = "CertificateAlias", targetNamespace = "") java.lang.String certificateAlias) throws com.sap.aii.tpm.internal.api.GetKeystoreCertificatesFault;

}
